# Site settings
title: The Maker Group
baseurl: ''
# url: http://maliagehan.github.io/maker-site

# Build settings
markdown: redcarpet
highlighter: pygments

# Jekyll-Bootstrap
JB:
    version: 2.0.3
    BASE_PATH : http://maliagehan.github.io/maker-site

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:

  - title: #facebook
    url:
  - title: twitter
    url: https://twitter.com/DDPSCmaker
  - title: #instagram
    url: 
  - title: #tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 975 North Warson Road,
    - St. Louis, Missouri 63132,
    - United States.
email: 
tel: 


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Noah Fahlgren
    position: Director of Bioinformatics Core
    text: Founding Member
    img: #team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Malia Gehan
    position: Assistant DDPSC Member and PI
    text: Founding Member
    img: #team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Max Feldman
    position: USDA Postdoctoral Researcher
    text: Active Member
    img: #team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Kazuhiro Kikuchi
    position: Postdoctoral Researcher
    text: Active Member
    img: #team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Dmitri Nusinow
    position: Assistant DDPSC Member and PI
    text: Active Member
    img: #team05.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Christine Shyu
    position: Postdoctoral Fellow
    text: Active Member
    img: #team06.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "The Maker Group at the Donald Danforth Plant Science Center is a forum for all members of the Center to explore constructing low-cost hardware and software engineering tools."
